---
- name: Include task to set up the swarm's manager
  include_tasks: docker-swarm-manager.yml
  when: "'{{ manager_ip }}' in ansible_all_ipv4_addresses"

- name: Save token needed to join swarm
  set_fact:
    join_token_worker: "{{ init_result.swarm_facts.JoinTokens.Worker }}"
  delegate_to: "{{ item }}"
  delegate_facts: True
  loop: "{{ groups['workers'] }}"
  when: "'{{ manager_ip }}' in ansible_all_ipv4_addresses"

- name: Add nodes to Docker swarm
  docker_swarm:
    state: join
    advertise_addr: "{{ manager_ip }}"
    join_token: "{{ join_token_worker }}"
    remote_addrs: "{{ manager_ip }}:2377"
  when: "'{{ manager_ip }}' not in ansible_all_ipv4_addresses"
