---
- name: Create folder for Docker's systemd configuration files
  file:
    path: "{{ dockerd_conf_folder }}"
    state: directory
    mode: 0755

- name: Create configuration file to expose Docker daemon API
  copy:
    force: no
    mode: 0644
    dest: "{{ dockerd_conf_folder }}/docker-external.conf"
    content: |
        [Service]
        ExecStart=
        ExecStart=/usr/bin/dockerd \
                  --tlsverify \
                  --tlscacert=/etc/ssl/certs/{{ ca_cert }}.crt \
                  --tlscert=/etc/ssl/certs/{{ server_cert }}.crt \
                  --tlskey=/etc/ssl/private/{{ server_key }}.pem \
                  -H tcp://0.0.0.0:2376 \
                  -H unix:///var/run/docker.sock

- name: Reload daemon and restart Docker service
  systemd:
    daemon_reload: yes
    state: restarted
    name: docker
