---
- name: Determine whether the current node is the manager
  set_fact:
    is_manager: "{% if manager_ip in ansible_all_ipv4_addresses %}true{% else %}false{% endif %}"

- name: Include task to set up the swarm's manager
  include_tasks: docker-swarm-manager.yml
  when: is_manager|bool

- name: Save token needed to join swarm
  set_fact:
    join_token_worker: "{{ init_result.swarm_facts.JoinTokens.Worker }}"
  delegate_to: "{{ item }}"
  delegate_facts: True
  loop: "{{ groups['workers'] }}"
  when: (is_manager|bool) and (init_result is defined)

- name: Add nodes to Docker swarm
  docker_swarm:
    state: join
    advertise_addr: "{{ manager_ip }}"
    join_token: "{{ join_token_worker }}"
    remote_addrs: "{{ manager_ip }}:2377"
  when: (not is_manager|bool) and (join_token_worker is defined)
