---
- name: Determine whether the current node is the manager
  set_fact:
    is_manager: "{% if manager_ip in ansible_all_ipv4_addresses %}true{% else %}false{% endif %}"

- name: Initalize a new Docker swarm
  docker_swarm:
    state: present
    advertise_addr: "{{ manager_ip }}"
  register: init_result
  when: is_manager|bool

- name: Get info on Docker Swarm
  docker_swarm_info:
  ignore_errors: yes
  register: result

- name: Inform about basic flags
  debug:
    msg: |
      Was able to talk to docker daemon: {{ result.can_talk_to_docker }}
      Docker in Swarm mode: {{ result.docker_swarm_active }}
      This is a Manager node: {{ result.docker_swarm_manager }}
