---
- name: Install and configure Docker and docker-compose
  include_tasks: docker-init-centos.yml
  when: ansible_distribution == 'CentOS'

- name: Generate TLS stuff for safely exposing the Docker daemon API
  include_tasks: docker-tls.yml

- name: Expose Docker daemon API
  include_tasks: docker-expose-api.yml

- name: Initialize a new Docker swarm
  include_tasks: docker-swarm.yml
